services:
  web: 
    build:
      context: app
      dockerfile: Dockerfile.app
    stop_signal: SIGINT
    ports:
      - '8000:8000'
  test:
    build:
      context: app
      dockerfile: Dockerfile.test